platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

def dependency_pods
	pod 'ObjectMapper', '~> 1.0'
	pod 'Alamofire', '~> 3.0'
end

target 'Plugin' do
  use_frameworks!
  pod 'GoogleMaps'
  capacitor_pods
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
  dependency_pods
end

target 'PluginTests' do
  use_frameworks!
  pod 'GoogleMaps'
  capacitor_pods
  dependency_pods
end
